### ISSUE TITLE
Add -ignore features!!

### ISSUE THREAD

**Issue by klee214** [VietnameZe/insane-cli#10]
## Requirements
The --ignore, -i, \i flag is optional, and if present should take a filepath and use it to load and parse an ignored URLs text file. If the ignore file isn't found, give an appropriate error message. Otherwise, all URLs should be checked against this list to see if they need to be ignored.
## example
```
# 2. File with a comment and single URL that matches any URL
# that starts with https://www.google.com, for example:
#
# https://www.google.com/index.html would match
# https://www.google.com/ would match
# https://www.google.ca would NOT match
https://www.google.com
```

**Comment by VietnameZe** [comment]
Yeah you're good to add it, I'll double check before merging your work. Thank you!

**Comment by VietnameZe** [comment]
Don't forget to edit README file as well

**Comment by klee214** [comment]
Sure!!!!!!!!!! :)

**Comment by klee214** [comment]
Hi again!! I am kind of done with this feature 
```
insane-cli sample.txt  -i ignore.txt
```
makes the test exclude URLs in ignore.txt.
I will make PR soon, I will let you know once I finish

**Comment by klee214** [comment]
the forked link is https://github.com/klee214/insane-cli. The branch name is issue-10.

**Comment by VietnameZe** [comment]
Merged! Thanks for your contributions!
