### ISSUE TITLE
Implementing another way would be better for performance?

### ISSUE THREAD

**Issue by StellaJung-Student** [VietnameZe/insane-cli#2]
When I tried to run insane-cli, it was very slow.
I think the reason is you use request with callback function so every request is running one by one which will cause slower.
Please use another way to handle with the callback function and also you can consider the options, method and timeout, to improve your performance.
https://github.com/request/request#requestoptions-callback.

**Comment by VietnameZe** [comment]
I did try to use timeout, the program seemed to be running faster but the results are not correct, majority of links will be in 'unknown' status, Idk which one should we go between: fast & wrong results VS slow & accurate results, still trying to implement it better but I think it's also depend on internet connection?
