### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by badalsarkar** [VietnameZe/insane-cli#6]
Hello Nguyen,
As part of lab 2, I would like to contribute to your application by implementing the following optional feature- 

* add a command line flag to allow checking for archived versions of URLs using the WayBackMachine

I will use cli option -w or /w. The input will be an URL and optional timestamp. The output will be the archived URL.

Please let me know if that is alright.

Thanks,
Badal

**Comment by VietnameZe** [comment]
Yeah why not? you're welcome to create pull requests
